### ISSUE TITLE
More obvious hover/focus styles

### ISSUE THREAD

**Issue by mathiasbynens** [necolas/css3-social-signin-buttons#1]
I love how the GitHub button’s background color changes when you hover/focus the link. For all the other buttons, this effect is much more subtle. Any chance of making the interaction styles for other buttons more obvious?

P.S. I’d love to help with this, but sadly I’m not a designer ;)

**Comment by necolas** [comment]
I tried to match the button and hover/active styles of any buttons (sign in or normal UI) that each service already has on their websites. So the GitHub one reflects their's and hopefully the others do too...although some services use static images so I added a subtle hover effect.

But maybe there are some hover/focus styles that will still work. I'll see if anyone has any nice suggestions. Thanks
