### ISSUE TITLE
FB/Twitter buttons just stopped working?

### ISSUE THREAD

**Issue by hasdavidc** [necolas/css3-social-signin-buttons#18]
I'm not quite sure what happened (as there hasn't been a commit in 9 months), but it appears that the Facebook and Twitter buttons (even on http://necolas.github.io/css3-social-signin-buttons/) have somehow stopped appearing.

**Comment by necolas** [comment]
looks fine to me

**Comment by hasdavidc** [comment]
hmm, weird - cleared my cache, but still not seeing on Chrome (v32) on Mac OS X, but shows up in private browsing mode. Safari looks good too... thanks anyway for the timely response
