### ISSUE TITLE
Facebook hover color can be overridden by default link styling

### ISSUE THREAD

**Issue by samgro** [necolas/css3-social-signin-buttons#4]
No hover color is specified, so if my stylesheet defines another default color for hover on links, we have a problem.

**Comment by lukashoffmann** [comment]
+1

**Comment by samgro** [comment]
@lukashoffman My fork fixes this for FB and Twitter: https://github.com/samgro/css3-social-signin-buttons

**Comment by lukashoffmann** [comment]
@samgro thx!
