### ISSUE TITLE
How about BrowserID?

### ISSUE THREAD

**Issue by ghost** [necolas/css3-social-signin-buttons#6]
Maybe it's not "social", but must be in, for the better tomorrow tomorrow.

**Comment by stefanfoulis** [comment]
+1 for adding BrowserID / Persona
here is a link to branding information for Persona: https://developer.mozilla.org/en-US/docs/persona/branding

**Comment by skorfmann** [comment]
Did you end up implementing this somewhere?

**Comment by stefanfoulis** [comment]
nope, not yet.
